apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gcs

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - app/deployment.yaml
  - app/service.yaml

images:
  - name: ghcr.io/zenuslouis/gcs-dashboard
    newTag: "37"
